### ISSUE TITLE
[BUG/English]: Login error 

### ISSUE THREAD

**Issue by engineerknow** [GamerNoTitle/Valora#152]
### Please select the Valora version you are using

Official Version https://val.bili33.top

### Please enter the URL where you encountered the issue (e.g., https://val.bili33.top/market)

https://val.bili33.top/login

### Please provide the steps to reproduce the issue

We're very sorry, there was an error on the server
500 Internal Server Error

The server encountered the following error
Traceback (most recent call last):
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\__init__.py", line 514, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 386, in decode
obj, end = self.raw_decode(s)
^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 416, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
response = self.full_dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
rv = self.handle_user_exception(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_profiler\flask_profiler.py", line 137, in wrapper
return wrapped(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_profiler\flask_profiler.py", line 109, in wrapper
returnVal = f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^
File "D:\WEB\Valora\app.py", line 238, in RiotLogin_handler
return RiotLogin(app, request)
^^^^^^^^^^^^^^^^^^^^^^^
File "D:\WEB\Valora\utils\api.py", line 41, in RiotLogin
user.auth()
File "D:\WEB\Valora\utils\RiotLogin.py", line 56, in auth
tokens = self.authorize(MFACode)
^^^^^^^^^^^^^^^^^^^^^^^
File "D:\WEB\Valora\utils\RiotLogin.py", line 94, in authorize
data = r.json()
^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

You can try refreshing this page or clicking the "Reset Site Data" button below to solve this problem.
If you have already clicked the button below but still encounter this problem, try clearing your browser's cookies to reset the session
If you have tried both of the above methods, please contact the developer with this error information!

### Please paste the logs displayed on the error page

```shell
The server encountered the following error
Traceback (most recent call last):
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\__init__.py", line 514, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 386, in decode
obj, end = self.raw_decode(s)
^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 416, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
response = self.full_dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
rv = self.handle_user_exception(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_profiler\flask_profiler.py", line 137, in wrapper
return wrapped(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_profiler\flask_profiler.py", line 109, in wrapper
returnVal = f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^
File "D:\WEB\Valora\app.py", line 238, in RiotLogin_handler
return RiotLogin(app, request)
^^^^^^^^^^^^^^^^^^^^^^^
File "D:\WEB\Valora\utils\api.py", line 41, in RiotLogin
user.auth()
File "D:\WEB\Valora\utils\RiotLogin.py", line 56, in auth
tokens = self.authorize(MFACode)
^^^^^^^^^^^^^^^^^^^^^^^
File "D:\WEB\Valora\utils\RiotLogin.py", line 94, in authorize
data = r.json()
^^^^^^^^
File "C:\Users\Mark-adev\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

You can try refreshing this page or clicking the "Reset Site Data" button below to solve this problem.
If you have already clicked the button below but still encounter this problem, try clearing your browser's cookies to reset the session
If you have tried both of the above methods, please contact the developer with this error information!
```

### Please provide screenshots of relevant information

-
![สกรีนช็อต 2024-06-12 225332](https://github.com/GamerNoTitle/Valora/assets/11179110/04d96a53-37e1-4862-af85-eaa181b09548)

### Any additional information? Please include it below

-
![สกรีนช็อต 2024-06-12 225332](https://github.com/GamerNoTitle/Valora/assets/11179110/adebf90b-8316-466c-a891-a3f0ab8faa32)

**Comment by GamerNoTitle** [comment]
It seems that you are using self-hosted Valora.
I wondered whether you run this on VPS or not. Currently, most of IPs of VPS server will be blocked by Cloudflare WAF and the login wheel was unable to bypass this. Since the WAF was hard to bypass, unless the login wheel got updated, or the login may not be successful.

**Comment by GamerNoTitle** [comment]
If you want more information, you can checkout #124

**Comment by GamerNoTitle** [comment]
Hello, I've tried using VPN to do the http request and it would work. If you cannot login, you can try using VPN.
